language: php
php:
 - 7.3.12

 before_install:
 - php /home/travis/build/pedrokarman/citas-medicas-/.vendor/autoload.php


before_script:
  - composer install 

# script: phpunit

matrix:
  allow_failures:
    - 7.3.12
  fast_finish: true


notifications:
    on_success: never
    on_failure: always
    email: cafranco4@poligran.edu.co



