language: php
php:
 - 7.3.12


before_script:
  - composer install 

script: phpunit -- configuration phpunit.xml

matrix:
  allow_failures:
    - 7.3.12
  fast_finish: true


# notifications:
#     on_success: never
#     on_failure: always



